package com.playerbrowser.app.web

import android.os.Handler
import android.os.Looper
import android.webkit.JavascriptInterface

/**
 * A `<video>` box on the page, in **device pixels relative to the WebView's
 * top-left**. `video_gestures.js` (`initInlinePlayer`) folds pinch-zoom
 * (`visualViewport.scale/offset`), `devicePixelRatio` and every ancestor
 * iframe's offset in before reporting, so Kotlin can place a native view over
 * it without knowing anything about the page's layout.
 */
data class InlineRect(val left: Int, val top: Int, val width: Int, val height: Int) {
    val isUsable: Boolean get() = width >= MIN_PX && height >= MIN_PX

    companion object {
        // Anything smaller is a thumbnail/preview, not a player worth replacing.
        const val MIN_PX = 96

        // Page-supplied numbers are untrusted: clamp to a sane screen-ish range
        // so a hostile script cannot ask for a 2^31-px layout.
        private const val MAX_PX = 16_384

        fun clamped(left: Int, top: Int, width: Int, height: Int): InlineRect = InlineRect(
            left = left.coerceIn(-MAX_PX, MAX_PX),
            top = top.coerceIn(-MAX_PX, MAX_PX),
            width = width.coerceIn(0, MAX_PX),
            height = height.coerceIn(0, MAX_PX)
        )
    }
}

/**
 * `window.PBInline` — the page → app side of the in-place player (v1.3.89).
 *
 * JS reports (1) a video that **started playing** together with its box and
 * current position, (2) box updates while the app is overlaying it, (3) the
 * video disappearing. Decisions (auto-replace on/off, is there a sniffed
 * stream?) stay in Kotlin — JS only observes. Commands flow the other way via
 * `evaluateJavascript("window.__pbInline.cmd(...)")`, see [InlinePlayerCommands].
 *
 * Every callback is marshalled to the main thread — WebView invokes
 * `@JavascriptInterface` methods on its own JS thread. Everything that
 * arrives here is page-controlled input: ids are length-capped, rects clamped.
 */
class InlinePlayerBridge(private val listener: Listener) {

    interface Listener {
        /** [manual] = the user picked "여기서 우리 플레이어로 재생" from the long-press menu. */
        fun onPlay(id: String, domSrc: String, positionSec: Double, rect: InlineRect, manual: Boolean)
        fun onRect(id: String, rect: InlineRect)
        fun onGone(id: String)
    }

    private val main = Handler(Looper.getMainLooper())

    @JavascriptInterface
    fun onPlay(
        id: String?, domSrc: String?, positionSec: Double,
        left: Int, top: Int, width: Int, height: Int, manual: Boolean
    ) {
        val vid = validId(id) ?: return
        val src = domSrc.orEmpty().take(MAX_SRC_LEN)
        val pos = if (positionSec.isFinite() && positionSec > 0) positionSec else 0.0
        val rect = InlineRect.clamped(left, top, width, height)
        main.post { listener.onPlay(vid, src, pos, rect, manual) }
    }

    @JavascriptInterface
    fun onRect(id: String?, left: Int, top: Int, width: Int, height: Int) {
        val vid = validId(id) ?: return
        val rect = InlineRect.clamped(left, top, width, height)
        main.post { listener.onRect(vid, rect) }
    }

    @JavascriptInterface
    fun onGone(id: String?) {
        val vid = validId(id) ?: return
        main.post { listener.onGone(vid) }
    }

    // Our JS makes ids as "<base36 prefix>-<counter>"; anything else is not ours.
    private fun validId(id: String?): String? =
        id?.takeIf { it.isNotBlank() && it.length <= MAX_ID_LEN && it.all { c -> c.isLetterOrDigit() || c == '-' || c == '_' } }

    private companion object {
        const val MAX_ID_LEN = 64
        const val MAX_SRC_LEN = 4096
    }
}

/** App → page commands for `window.__pbInline.cmd(json)`. */
object InlinePlayerCommands {
    /** Pause + mute the site's video and start streaming its box to [InlinePlayerBridge.onRect]. */
    fun take(id: String): String = cmd("{\"kind\":\"take\",\"id\":${quote(id)}}")

    /** Re-report the video the user just long-pressed as a manual take request. */
    fun pressed(): String = cmd("{\"kind\":\"pressed\"}")

    /** Hand the video back to the site: stop tracking, unmute, seek to [positionSec], stay paused. */
    fun release(id: String, positionSec: Double): String {
        // -1 = unknown: JS skips the seek instead of rewinding the site video to 0.
        val pos = if (positionSec.isFinite() && positionSec >= 0) positionSec else -1.0
        return cmd("{\"kind\":\"release\",\"id\":${quote(id)},\"pos\":$pos}")
    }

    private fun cmd(json: String): String =
        "(function(){try{if(window.__pbInline)window.__pbInline.cmd($json);}catch(e){}})();"

    // Ids are generated by our own JS (base36 + counter) but quote defensively anyway.
    private fun quote(s: String): String = buildString {
        append('"')
        for (c in s) when {
            c == '"' -> append("\\\"")
            c == '\\' -> append("\\\\")
            c < ' ' -> append(' ')
            else -> append(c)
        }
        append('"')
    }
}
